/* Name to function binding table.
 *
 * This table gives the names of all the bindable functions
 * end their C function address. These are used for the bind-to-key
 * function.
*/

#include "estruct.h"
#include "edef.h"
#include "efunc.h"
#include "line.h"

struct name_bind names[] = {
	{"abort-command", ctrlg},
	{"add-global-mode", setgmode},
	{"add-mode", setemode},
	{"apropos", apropos_command},
	{"backward-character", move_char_backward},
	{"begin-macro", ctlxlp},
	{"beginning-of-file", goto_buffer_start},
	{"beginning-of-line", goto_line_start},
	{"bind-to-key", bindtokey},
	{"buffer-position", showcpos},
	{"case-region-lower", lowerregion},
	{"case-region-upper", upperregion},
	{"case-word-capitalize", capword},
	{"case-word-lower", lowerword},
	{"case-word-upper", upperword},
	{"change-file-name", filename},
	{"change-screen-size", newsize},
	{"change-screen-width", newwidth},
	{"clear-and-redraw", redraw},
	{"clear-message-line", clrmes},
	{"copy-region", region_copy},
	{"count-words", wordcount},
	{"ctlx-prefix", cex},
	{"decrypt-file", decrypt_file_gpg},
	{"decrypt-file-age", decrypt_file_age},
	{"delete-blank-lines", deblank},
	{"delete-buffer", killbuffer},
	{"delete-global-mode", delgmode},
	{"delete-mode", delmode},
	{"delete-next-character", delete_char_forward},
	{"delete-next-word", delete_word_forward},
	{"delete-other-windows", window_only},
	{"delete-previous-character", delete_char_backward},
	{"delete-previous-word", delete_word_backward},
	{"delete-window", window_delete},
	{"describe-bindings", describe_all_bindings},
	{"describe-key", describe_key_binding},
	{"detab-line", detab},
	{"disable-help-prefix", help_prefix_disable},
	{"duplicate-line", duplicate_line},
	{"enable-help-prefix", help_prefix_enable},
	{"encrypt-buffer", encrypt_buffer_gpg},
	{"encrypt-buffer-age", encrypt_buffer_age},
	{"encrypt-buffer-auto", encrypt_buffer_auto},
	{"end-macro", ctlxrp},
	{"end-of-file", goto_buffer_end},
	{"end-of-line", goto_line_end},
	{"entab-line", entab},
	{"evil-mode", evil_mode},
	{"exchange-point-and-mark", swapmark},
	{"execute-buffer", execbuf},
	{"execute-command-line", execcmd},
	{"execute-file", execfile},
	{"execute-macro", ctlxe},
	{"execute-macro-1", cbuf1},
	{"execute-macro-10", cbuf10},
	{"execute-macro-11", cbuf11},
	{"execute-macro-12", cbuf12},
	{"execute-macro-13", cbuf13},
	{"execute-macro-14", cbuf14},
	{"execute-macro-15", cbuf15},
	{"execute-macro-16", cbuf16},
	{"execute-macro-17", cbuf17},
	{"execute-macro-18", cbuf18},
	{"execute-macro-19", cbuf19},
	{"execute-macro-2", cbuf2},
	{"execute-macro-20", cbuf20},
	{"execute-macro-21", cbuf21},
	{"execute-macro-22", cbuf22},
	{"execute-macro-23", cbuf23},
	{"execute-macro-24", cbuf24},
	{"execute-macro-25", cbuf25},
	{"execute-macro-26", cbuf26},
	{"execute-macro-27", cbuf27},
	{"execute-macro-28", cbuf28},
	{"execute-macro-29", cbuf29},
	{"execute-macro-3", cbuf3},
	{"execute-macro-30", cbuf30},
	{"execute-macro-31", cbuf31},
	{"execute-macro-32", cbuf32},
	{"execute-macro-33", cbuf33},
	{"execute-macro-34", cbuf34},
	{"execute-macro-35", cbuf35},
	{"execute-macro-36", cbuf36},
	{"execute-macro-37", cbuf37},
	{"execute-macro-38", cbuf38},
	{"execute-macro-39", cbuf39},
	{"execute-macro-4", cbuf4},
	{"execute-macro-40", cbuf40},
	{"execute-macro-5", cbuf5},
	{"execute-macro-6", cbuf6},
	{"execute-macro-7", cbuf7},
	{"execute-macro-8", cbuf8},
	{"execute-macro-9", cbuf9},
	{"execute-named-command", namedcmd},
	{"execute-procedure", execproc},
	{"execute-program", execprg},
	{"exit-emacs", quit},
	{"exit-writing-mode", writing_mode_disable},
	{"fill-paragraph", fillpara},
	{"filter-buffer", filter_buffer},
	{"find-file", filefind},
	{"forward-character", move_char_forward},
	{"goto-line", gotoline},
	{"goto-matching-fence", getfence},
	{"grow-window", window_enlarge},
	{"handle-tab", insert_tab},
	{"help", help},
	{"hunt-backward", backhunt},
	{"hunt-forward", forwhunt},
	{"i-shell", spawncli},
	{"incremental-search", fisearch},
	{"insert-file", insfile},
	{"insert-space", insspace},
	{"insert-string", istring},
	{"justify-paragraph", justpara},
	{"keymap-stats", keymap_stats_cmd},
	{"kill-paragraph", killpara},
	{"kill-region", region_kill},
	{"kill-to-end-of-line", kill_to_eol},
	{"list-buffers", listbuffers},
	{"list-settings", list_settings_cmd},
	{"local-set-key", localsetkey},
	{"local-unset-key", localunsetkey},
	{"meta-prefix", metafn},
	{"move-line-down", transpose_line_down},
	{"move-line-up", transpose_line_up},
	{"move-window-down", window_move_down},
	{"move-window-up", window_move_up},
	{"name-buffer", namebuffer},
	{"newline", insert_newline},
	{"newline-and-indent", indent},
	{"next-buffer", nextbuffer},
	{"next-line", cursor_down},
	{"next-page", move_page_down},
	{"next-paragraph", goto_para_end},
	{"next-subword", forwsubword},
	{"next-window", window_next},
	{"next-word", move_word_forward},
	{"nop", nullproc},
	{"open-line", openline},
	{"open-user-config", open_user_config_cmd},
	{"overwrite-string", ovstring},
	{"pipe-command", pipecmd},
	{"previous-line", cursor_up},
	{"previous-page", move_page_up},
	{"previous-paragraph", goto_para_start},
	{"previous-subword", backsubword},
	{"previous-window", window_prev},
	{"previous-word", move_word_backward},
	{"query-replace-string", qreplace},
	{"quick-exit", quickexit},
	{"quote-character", quote},
	{"read-file", fileread},
	{"redo", redo_cmd},
	{"redraw-display", reposition},
	{"replace-string", sreplace},
/* Non-Linux specific commands removed — keep command set minimal */
	{"resize-window", resize},
	{"restore-window", window_restore},
	{"reverse-incremental-search", risearch},
	{"run", execproc},
	{"save-file", filesave},
	{"save-settings", save_settings_cmd},
/* Session commands removed — keep interface simple */
	{"save-window", window_save},
	{"scroll-next-down", scroll_other_down},
	{"scroll-next-up", scroll_other_up},
	{"search-forward", forwsearch},
	{"search-reverse", backsearch},
	{"select-buffer", usebuffer},
	{"set", setvar},
	{"set-column-width", set_column_width_cmd},
	{"set-mark", setmark},
	{"shell-command", spawn},
	{"show-encryption-tools", show_encryption_tools},
	{"shrink-window", window_shrink},
	{"soft-wrap", soft_wrap_toggle_cmd},
	{"soft-wrap-column", soft_wrap_column_cmd},
	{"split-current-window", window_split},
	{"store-macro", storemac},
	{"store-procedure", storeproc},
	{"suspend-emacs", bktoshell},
	{"term", terminal_buffer_open},
	{"term-close", terminal_close},
	{"terminal-buffer", terminal_buffer_open},
	{"terminal-close", terminal_close},
	{"transpose-characters", twiddle},
	{"trim-line", trim},
	{"unbind-key", unbindkey},
	{"undo", undo_cmd},
	{"universal-argument", unarg},
	{"unmark-buffer", unmark},
	{"update-screen", upscreen},
	{"view-file", viewfile},
	{"vim-append", vim_append},
	{"vim-append-eol", vim_append_eol},
	{"vim-change-operator", vim_change_operator},
	{"vim-delete-char", vim_delete_char},
	{"vim-delete-operator", vim_delete_operator},
	{"vim-digit-0", vim_digit_0},
	{"vim-digit-1", vim_digit_1},
	{"vim-digit-2", vim_digit_2},
	{"vim-digit-3", vim_digit_3},
	{"vim-digit-4", vim_digit_4},
	{"vim-digit-5", vim_digit_5},
	{"vim-digit-6", vim_digit_6},
	{"vim-digit-7", vim_digit_7},
	{"vim-digit-8", vim_digit_8},
	{"vim-digit-9", vim_digit_9},
	{"vim-dot-repeat", vim_dot_repeat},
	{"vim-end-of-word", vim_end_of_word},
	{"vim-enter-insert-mode", vim_enter_insert_mode},
	{"vim-enter-normal-mode", vim_enter_normal_mode},
	{"vim-enter-replace-mode", vim_enter_replace_mode},
	{"vim-enter-visual-line-mode", vim_enter_visual_line_mode},
	{"vim-enter-visual-mode", vim_enter_visual_mode},
	{"vim-exit-visual-mode", vim_exit_visual_mode},
	{"vim-find-char-backward", vim_find_char_backward},
	{"vim-find-char-forward", vim_find_char_forward},
	{"vim-first-nonblank", vim_first_nonblank},
	{"vim-first-nonblank-wrapped", vim_first_nonblank_wrapped},
	{"vim-goto-line-or-end", vim_goto_line_or_end},
	{"vim-goto-mark-exact", vim_goto_mark_exact},
	{"vim-goto-mark-line", vim_goto_mark_line},
	{"vim-goto-prefix", vim_goto_prefix},
	{"vim-goto-top", vim_goto_top},
	{"vim-insert-bol", vim_insert_bol},
	{"vim-line-end", vim_line_end},
	{"vim-line-start", vim_line_start},
	{"vim-move-down", vim_move_down},
	{"vim-move-left", vim_move_left},
	{"vim-move-right", vim_move_right},
	{"vim-move-up", vim_move_up},
	{"vim-open-line-above", vim_open_line_above},
	{"vim-open-line-below", vim_open_line_below},
	{"vim-put-after", vim_put_after},
	{"vim-put-before", vim_put_before},
	{"vim-register-prefix", vim_register_prefix},
	{"vim-repeat-find", vim_repeat_find},
	{"vim-repeat-find-reverse", vim_repeat_find_reverse},
	{"vim-replace-char", vim_replace_char},
	{"vim-search-backward", vim_search_backward},
	{"vim-search-forward", vim_search_forward},
	{"vim-search-next", vim_search_next},
	{"vim-search-prev", vim_search_prev},
	{"vim-search-word-backward", vim_search_word_backward},
	{"vim-search-word-forward", vim_search_word_forward},
	{"vim-set-mark", vim_set_mark},
	{"vim-text-object-around", vim_text_object_around},
	{"vim-text-object-inner", vim_text_object_inner},
	{"vim-till-char-backward", vim_till_char_backward},
	{"vim-till-char-forward", vim_till_char_forward},
	{"vim-toggle-case", vim_toggle_case},
	{"vim-visual-change", vim_visual_change},
	{"vim-visual-delete", vim_visual_delete},
	{"vim-visual-yank", vim_visual_yank},
	{"vim-word-backward", vim_word_backward},
	{"vim-word-end", vim_word_end},
	{"vim-word-forward", vim_word_forward},
	{"vim-yank-operator", vim_yank_operator},
	{"wrap-word", wrapword},
	{"write-edit", write_edit_cmd},
	{"write-file", filewrite},
	{"write-message", writemsg},
	{"writing-mode", writing_mode_enable},
	{"yank", yank},
	{"yank-clipboard", yank_clipboard},
	{"yank-pop", yankpop},

	{nullptr, nullptr}  /* Sentinel - must be nullptr, not empty string */
};

/* Compile-time verification that names table has minimum size */
static_assert(
	sizeof(names) > 2 * sizeof(struct name_bind),
	"names table must have at least 2 entries"
);

#ifdef DEBUG
/* Runtime verification that names table is sorted (call once at startup) */
void verify_names_sorted(void) {
	for (size_t i = 1; names[i].n_name != nullptr; i++) {
		if (strcmp(names[i-1].n_name, names[i].n_name) >= 0) {
			fprintf(stderr, "ERROR: names[] not sorted at index %zu: '%s' >= '%s'\n",
				i, names[i-1].n_name, names[i].n_name);
			abort();
		}
	}
}
#endif
