/* Name to function binding table.
 *
 * This table gives the names of all the bindable functions
 * end their C function address. These are used for the bind-to-key
 * function.
*/

#include "estruct.h"
#include "edef.h"
#include "efunc.h"
#include "line.h"

struct name_bind names[] = {
	{"abort-command", ctrlg},
	{"add-global-mode", setgmode},
	{"add-mode", setemode},
	{"apropos", apropos_command},
	{"backward-character", move_char_backward},
	{"begin-macro", ctlxlp},
	{"beginning-of-file", goto_buffer_start},
	{"beginning-of-line", goto_line_start},
	{"bind-to-key", bindtokey},
	{"buffer-position", showcpos},
	{"build-next-error", build_next_error},
	{"build-prev-error", build_prev_error},
	{"build-run", build_run},
	{"case-region-lower", lowerregion},
	{"case-region-upper", upperregion},
	{"case-word-capitalize", capword},
	{"case-word-lower", lowerword},
	{"case-word-upper", upperword},
	{"change-file-name", filename},
	{"change-screen-size", newsize},
	{"change-screen-width", newwidth},
	{"clear-and-redraw", redraw},
	{"clear-message-line", clrmes},
	{"clipboard-provider", clipboard_provider_cmd},
	{"copy-region", region_copy},
	{"copy-to-clipboard", copy_to_clipboard},
	{"count-words", wordcount},
	{"ctlx-prefix", cex},
	{"decrypt-file", decrypt_file_gpg},
	{"decrypt-file-age", decrypt_file_age},
	{"delete-blank-lines", deblank},
	{"delete-buffer", killbuffer},
	{"delete-global-mode", delgmode},
	{"delete-mode", delmode},
	{"delete-next-character", delete_char_forward},
	{"delete-next-word", delete_word_forward},
	{"delete-other-windows", window_only},
	{"delete-previous-character", delete_char_backward},
	{"delete-previous-word", delete_word_backward},
	{"delete-window", window_delete},
	{"describe-bindings", describe_all_bindings},
	{"describe-key", describe_key_binding},
	{"detab-line", detab},
	{"disable-help-prefix", help_prefix_disable},
	{"duplicate-line", duplicate_line},
	{"enable-help-prefix", help_prefix_enable},
	{"encrypt-buffer", encrypt_buffer_gpg},
	{"encrypt-buffer-age", encrypt_buffer_age},
	{"encrypt-buffer-auto", encrypt_buffer_auto},
	{"end-macro", ctlxrp},
	{"end-of-file", goto_buffer_end},
	{"end-of-line", goto_line_end},
	{"entab-line", entab},
	{"evil-mode", evil_mode},
	{"exchange-point-and-mark", swapmark},
	{"execute-buffer", execbuf},
	{"execute-command-line", execcmd},
	{"execute-file", execfile},
	{"execute-macro", ctlxe},
	{"execute-macro-1", cbuf1},
	{"execute-macro-10", cbuf10},
	{"execute-macro-11", cbuf11},
	{"execute-macro-12", cbuf12},
	{"execute-macro-13", cbuf13},
	{"execute-macro-14", cbuf14},
	{"execute-macro-15", cbuf15},
	{"execute-macro-16", cbuf16},
	{"execute-macro-17", cbuf17},
	{"execute-macro-18", cbuf18},
	{"execute-macro-19", cbuf19},
	{"execute-macro-2", cbuf2},
	{"execute-macro-20", cbuf20},
	{"execute-macro-21", cbuf21},
	{"execute-macro-22", cbuf22},
	{"execute-macro-23", cbuf23},
	{"execute-macro-24", cbuf24},
	{"execute-macro-25", cbuf25},
	{"execute-macro-26", cbuf26},
	{"execute-macro-27", cbuf27},
	{"execute-macro-28", cbuf28},
	{"execute-macro-29", cbuf29},
	{"execute-macro-3", cbuf3},
	{"execute-macro-30", cbuf30},
	{"execute-macro-31", cbuf31},
	{"execute-macro-32", cbuf32},
	{"execute-macro-33", cbuf33},
	{"execute-macro-34", cbuf34},
	{"execute-macro-35", cbuf35},
	{"execute-macro-36", cbuf36},
	{"execute-macro-37", cbuf37},
	{"execute-macro-38", cbuf38},
	{"execute-macro-39", cbuf39},
	{"execute-macro-4", cbuf4},
	{"execute-macro-40", cbuf40},
	{"execute-macro-5", cbuf5},
	{"execute-macro-6", cbuf6},
	{"execute-macro-7", cbuf7},
	{"execute-macro-8", cbuf8},
	{"execute-macro-9", cbuf9},
	{"execute-named-command", namedcmd},
	{"execute-procedure", execproc},
	{"execute-program", execprg},
	{"exit-emacs", quit},
	{"exit-writing-mode", writing_mode_disable},
	{"extension-list", extension_list_cmd},
	{"extension-load", extension_load_cmd},
	{"extension-unload", extension_unload_cmd},
	{"fill-paragraph", fillpara},
	{"filter-buffer", filter_buffer},
	{"find-file", filefind},
	{"forward-character", move_char_forward},
	{"goto-line", gotoline},
	{"goto-matching-fence", getfence},
	{"grow-window", window_enlarge},
	{"handle-tab", insert_tab},
	{"help", help},
	{"hunt-backward", backhunt},
	{"hunt-forward", forwhunt},
	{"i-shell", spawncli},
	{"incremental-search", fisearch},
	{"insert-file", insfile},
	{"insert-space", insspace},
	{"insert-string", istring},
	{"justify-paragraph", justpara},
	{"keymap-stats", keymap_stats_cmd},
	{"kill-paragraph", killpara},
	{"kill-region", region_kill},
	{"kill-to-end-of-line", kill_to_eol},
	{"list-buffers", listbuffers},
	{"list-settings", list_settings_cmd},
	{"local-set-key", localsetkey},
	{"local-unset-key", localunsetkey},
	{"meta-prefix", metafn},
	{"move-line-down", transpose_line_down},
	{"move-line-up", transpose_line_up},
	{"move-window-down", window_move_down},
	{"move-window-up", window_move_up},
	{"name-buffer", namebuffer},
	{"newline", insert_newline},
	{"newline-and-indent", indent},
	{"next-buffer", nextbuffer},
	{"next-line", cursor_down},
	{"next-page", move_page_down},
	{"next-paragraph", goto_para_end},
	{"next-subword", forwsubword},
	{"next-window", window_next},
	{"next-word", move_word_forward},
	{"nop", nullproc},
	{"open-line", openline},
	{"open-user-config", open_user_config_cmd},
	{"overwrite-string", ovstring},
	{"pipe-command", pipecmd},
	{"previous-line", cursor_up},
	{"previous-page", move_page_up},
	{"previous-paragraph", goto_para_start},
	{"previous-subword", backsubword},
	{"previous-window", window_prev},
	{"previous-word", move_word_backward},
	{"query-replace-string", qreplace},
	{"quick-exit", quickexit},
	{"quote-character", quote},
	{"read-file", fileread},
	{"redo", redo_cmd},
	{"redraw-display", reposition},
	{"repl-eval-buffer", repl_eval_buffer},
	{"repl-eval-line", repl_eval_line},
	{"repl-eval-region", repl_eval_region},
	{"repl-start", repl_start},
	{"replace-string", sreplace},
/* Non-Linux specific commands removed — keep command set minimal */
	{"resize-window", resize},
	{"restore-window", window_restore},
	{"reverse-incremental-search", risearch},
	{"run", execproc},
	{"save-file", filesave},
	{"save-settings", save_settings_cmd},
/* Session commands removed — keep interface simple */
	{"save-window", window_save},
	{"scripts-list", uep_scripts_list_cmd},
	{"scripts-reload", uep_scripts_reload_cmd},
	{"scroll-next-down", scroll_other_down},
	{"scroll-next-up", scroll_other_up},
	{"search-forward", forwsearch},
	{"search-reverse", backsearch},
	{"select-buffer", usebuffer},
	{"set", setvar},
	{"set-column-width", set_column_width_cmd},
	{"set-mark", setmark},
	{"shell-command", spawn},
	{"show-encryption-tools", show_encryption_tools},
	{"shrink-window", window_shrink},
	{"soft-wrap", soft_wrap_toggle_cmd},
	{"soft-wrap-column", soft_wrap_column_cmd},
	{"split-current-window", window_split},
	{"store-macro", storemac},
	{"store-procedure", storeproc},
	{"suspend-emacs", bktoshell},
	{"term", terminal_buffer_open},
	{"term-close", terminal_close},
	{"terminal-buffer", terminal_buffer_open},
	{"terminal-capture", terminal_capture},
	{"terminal-close", terminal_close},
	{"terminal-create", terminal_create},
	{"terminal-list", terminal_list},
	{"terminal-send-buffer", terminal_send_buffer},
	{"terminal-send-line", terminal_send_line},
	{"terminal-send-region", terminal_send_region},
	{"terminal-switch", terminal_switch},
	{"terminal-toggle", terminal_toggle},
	{"transpose-characters", twiddle},
	{"trim-line", trim},
	{"uep-format-buffer", uep_format_buffer},
	{"unbind-key", unbindkey},
	{"undo", undo_cmd},
	{"universal-argument", unarg},
	{"unmark-buffer", unmark},
	{"update-screen", upscreen},
	{"view-file", viewfile},
	{"wrap-word", wrapword},
	{"write-file", filewrite},
	{"write-message", writemsg},
	{"writing-mode", writing_mode_enable},
	{"yank", yank},
	{"yank-clipboard", yank_clipboard},
	{"yank-pop", yankpop},

	{nullptr, nullptr}  /* Sentinel - must be nullptr, not empty string */
};

/* Compile-time verification that names table has minimum size */
static_assert(
	sizeof(names) > 2 * sizeof(struct name_bind),
	"names table must have at least 2 entries"
);

#ifdef DEBUG
/* Runtime verification that names table is sorted (call once at startup) */
void verify_names_sorted(void) {
	for (size_t i = 1; names[i].n_name != nullptr; i++) {
		if (strcmp(names[i-1].n_name, names[i].n_name) >= 0) {
			fprintf(stderr, "ERROR: names[] not sorted at index %zu: '%s' >= '%s'\n",
				i, names[i-1].n_name, names[i].n_name);
			abort();
		}
	}
}
#endif
